theme = "gruvbox_dark_hard"

[editor]
rulers = [
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.whitespace.render]
tab = "all"

[editor.soft-wrap]
enable = true
