colorscheme desertex

set global scrolloff 5,0

add-highlighter global wrap -word -indent

def RemoveTrailingWhitespace %{
    execute-keys "\%s\h+$<ret>d;"
}

hook global WinSetOption filetype=go %{
    set window lintcmd kakgolint.sh
    lint-enable
    hook buffer BufWritePost .* lint
}

# auto indent/dedent with tab in insert-mode
map global insert <tab> '<a-;><gt>'
map global insert <backtab> '<a-;><lt>'
