[theme]
name = "gruvbox-dark"
[theme.overrides]
idle_bg = "#282828"
idle_fg = "#ebdbb2"
info_bg = "#282828"
info_fg = "#ebdbb2"
good_bg = "#282828"
good_fg = "#ebdbb2"
warning_bg = "#282828"
warning_fg = "#fb4934"

[icons]
name = "awesome"

[[block]]
block = "uptime"

[block.theme_overrides]
idle_fg = "#e5786d"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 1
warning = 20
alert = 0
alert_absolute = true
format = "{path}{available}"

[block.theme_overrides]
idle_fg = "#50fc50"

[[block]]
block = "battery"
interval = 1

[block.theme_overrides]
idle_fg = "#ffad33"
idle_bg = "#282828"
good_fg = "#ffad33"
good_bg = "#282828"

[[block]]
block = "net"
format = "{ssid} {speed_down} {speed_up}"

[block.theme_overrides]
idle_fg = "#f8fc50"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"
format_swap = "{swap_used}"

[block.theme_overrides]
idle_fg = "#77a7e5"
good_fg = "#77a7e5"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[block.theme_overrides]
idle_fg = "#f854f8"
good_fg = "#f854f8"

[[block]]
block = "sound"

[block.theme_overrides]
idle_fg = "#50fcf8"

[[block]]
block = "time"
interval = 1
format = "%Y-%m-%d %H:%M:%S"
