[theme]
theme = "gruvbox-dark"
[theme.overrides]
idle_bg = "#282828"
idle_fg = "#ebdbb2"
info_bg = "#282828"
info_fg = "#ebdbb2"
good_bg = "#282828"
good_fg = "#ebdbb2"
warning_bg = "#282828"
warning_fg = "#fb4934"

[icons]
icons = "awesome4"

[[block]]
block = "uptime"

[block.theme_overrides]
idle_fg = "#e5786d"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 1
warning = 20
alert = 10
format = "/ $available.eng(w:2)"

[block.theme_overrides]
idle_fg = "#50fc50"

[[block]]
block = "battery"
interval = 1

[block.theme_overrides]
idle_fg = "#ffad33"
idle_bg = "#282828"
good_fg = "#ffad33"
good_bg = "#282828"

[[block]]
block = "net"
format = "$ssid ^icon_net_down$speed_down.eng(prefix:K) ^icon_net_up$speed_up.eng(prefix:K)"

[block.theme_overrides]
idle_fg = "#f8fc50"

[[block]]
block = "memory"
format = "$icon$mem_used.eng(w:3,u:B,p:M)"
format_alt = " $icon_swap$swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M) "

[block.theme_overrides]
idle_fg = "#77a7e5"
good_fg = "#77a7e5"

[[block]]
block = "load"
interval = 1
format = "$icon$1m.eng(w:4)"

[block.theme_overrides]
idle_fg = "#f854f8"
good_fg = "#f854f8"

[[block]]
block = "sound"

[block.theme_overrides]
idle_fg = "#50fcf8"

[[block]]
block = "time"
interval = 1
format = "$icon $timestamp.datetime(f:'%Y-%m-%d %H:%M:%S')"
